[tool.poetry]
name = "chat"
version = "0.1.0"
description = ""
authors = ["cneill <cneill@indeed.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
openai = "^1.64.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
